version: "3.3"
    
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    build: .
    volumes:
      - ./html:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      PHP_EXTENSION_XDEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  
